name: Sygna Assembly Checker
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  checker:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.DEVOPS_CHANGELOG_TOKEN }}
    steps:
      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CLONE_BOT_APP_ID }}
          private-key: ${{ secrets.CLONE_BOT_PRIVATE_KEY }}
          # 限制只存取需要的 repository
          repositories: 'sygna-bridge-assembly-handler'
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print working directory
        run: pwd && ls -lah

      - name: Checkout assembly handler
        env:
          TOKEN: ${{ steps.generate-token.outputs.token }}
          ENV: ${{ github.head_ref }}
        run: |
          if [[ $ENV == "master" || $ENV == "test" ]]
          then
            git clone --branch $ENV --depth 1 https://x-access-token:${TOKEN}@github.com/sygnaio/sygna-bridge-assembly-handler.git handler
          else
            git clone --branch dev --depth 1 https://x-access-token:${TOKEN}@github.com/sygnaio/sygna-bridge-assembly-handler.git handler
          fi

      - name: Run checker
        run: |
          cd handler
          npm ci
          npm run check
